semi: true
singleQuote: true
useTabs: false
tabWidth: 2
trailingComma: es5
printWidth: 80
endOfLine: lf
arrowParens: always
bracketSpacing: true
embeddedLanguageFormatting: auto
plugins:
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: true
